const std = @import("std");
const fs = std.fs;
const Allocator = std.mem.Allocator;
const zion_root = @import("root.zig");
const Dir = std.Io.Dir;
const Io = std.Io;

const add_cmd = @import("commands/add.zig");
const remove_cmd = @import("commands/remove.zig");
const manifest = @import("manifest.zig");
const ghostspec_pkg = @import("ghostspec");

const scaffold_template = @embedFile("templates/ghostspec_suite.zig");
const build_wiring_snippet =
    "    // GhostSpec integration (generated by Zion)\n" ++ "    const ghostspec_dep = b.dependency(\"ghostspec\", .{ .target = target, .optimize = optimize });\n" ++ "    const ghostspec_artifacts = ghostspec.zion.addBuildSteps(b, ghostspec_dep, .{\n" ++ "        .step_name = \"ghostspec-test\",\n" ++ "        .step_description = \"Run GhostSpec test suites\",\n" ++ "    });\n" ++ "    test_step.dependOn(&ghostspec_artifacts.test_step.step);\n\n";

pub const default_suite_path = "tests/ghostspec_suite.zig";
pub const default_report_path = ".zion/ghostspec/run.json";

pub const InstallOptions = struct {
    update: bool = false,
    auto_wire: bool = true,
    scaffold: bool = false,
    force_scaffold: bool = false,
};

pub const BootstrapOptions = struct {
    force_scaffold: bool = false,
};

pub const ScaffoldOptions = struct {
    force: bool = false,
    destination: []const u8 = default_suite_path,
};

pub const InstallResult = struct {
    dependency_added: bool = false,
    build_wired: bool = false,
    scaffolded: bool = false,
    artifact_dirs_created: bool = false,
};

pub const RunMode = enum {
    run,
    fuzz,
    bench,
    report,
    ci,
};

pub const CommandFailed = error{ CommandFailed, SpawnFailed };

pub fn install(allocator: Allocator, options: InstallOptions) !InstallResult {
    var result = InstallResult{};

    result.dependency_added = try ensureDependency(allocator, options.update);

    if (options.auto_wire) {
        result.build_wired = try ensureBuildIntegration(allocator);
    }

    result.artifact_dirs_created = try ensureArtifactLayout();

    if (options.scaffold) {
        result.scaffolded = try scaffoldSuite(allocator, .{
            .force = options.force_scaffold,
        });
    }

    return result;
}

pub fn bootstrap(allocator: Allocator, options: BootstrapOptions) !InstallResult {
    return install(allocator, .{
        .update = false,
        .auto_wire = true,
        .scaffold = true,
        .force_scaffold = options.force_scaffold,
    });
}

pub fn uninstall(allocator: Allocator) !void {
    try remove_cmd.remove(allocator, "ghostspec");
}

pub fn ensureBuildIntegration(allocator: Allocator) !bool {
    const io = try zion_root.getIo();
    const cwd = Dir.cwd();
    const build_path = "build.zig";

    const raw = cwd.readFileAlloc(io, build_path, allocator, Io.Limit.limited(1024 * 1024)) catch |err| {
        if (err == error.FileNotFound) {
            std.debug.print("build.zig not found; skipping automatic wiring.\n", .{});
            return false;
        }
        return err;
    };
    defer allocator.free(raw);

    if (std.mem.indexOf(u8, raw, "ghostspec.zion.addBuildSteps") != null) {
        return false;
    }

    const snippet = buildSnippet();
    const anchor = "test_step.dependOn(&run_exe_tests.step);\n";

    const updated = try blk: {
        if (std.mem.indexOf(u8, raw, anchor)) |pos| {
            const insert_pos = pos + anchor.len;
            const parts = [_][]const u8{ raw[0..insert_pos], snippet, raw[insert_pos..] };
            break :blk std.mem.concat(allocator, u8, &parts);
        } else {
            const trimmed = std.mem.trimEnd(u8, raw, " \n\t");
            const brace_index = std.mem.lastIndexOfScalar(u8, trimmed, '}') orelse return error.InvalidBuildFile;
            const parts = [_][]const u8{ raw[0..brace_index], snippet, raw[brace_index..] };
            break :blk std.mem.concat(allocator, u8, &parts);
        }
    };
    defer allocator.free(updated);

    const file = try cwd.createFile(io, build_path, .{ .truncate = true });
    defer file.close(io);
    try file.writeStreamingAll(io, updated);
    std.debug.print("Added GhostSpec build wiring to build.zig.\n", .{});
    return true;
}

pub fn scaffoldSuite(allocator: Allocator, options: ScaffoldOptions) !bool {
    _ = allocator;
    const io = try zion_root.getIo();
    const cwd = Dir.cwd();
    const dest = options.destination;
    const dir_path = std.fs.path.dirname(dest) orelse ".";

    cwd.createDirPath(io, dir_path) catch |err| {
        if (err != error.PathAlreadyExists) return err;
    };

    if (!options.force) {
        cwd.access(io, dest, .{}) catch |err| {
            if (err != error.FileNotFound) return err;
            // File doesn't exist, continue to create it
        };
        // If access succeeded, file exists
        if (!options.force) {
            cwd.access(io, dest, .{}) catch {
                // File doesn't exist, continue to create
            };
            // Check again to see if file exists
            const file_exists = blk: {
                cwd.access(io, dest, .{}) catch break :blk false;
                break :blk true;
            };
            if (file_exists) {
                std.debug.print("{s} already exists; use --force to overwrite.\n", .{dest});
                return false;
            }
        }
    }

    const file = cwd.createFile(io, dest, .{
        .truncate = true,
    }) catch |err| {
        if (err == error.PathAlreadyExists) {
            return false;
        }
        return err;
    };
    defer file.close(io);

    try file.writeStreamingAll(io, scaffold_template);
    std.debug.print("Wrote GhostSpec suite scaffold to {s}.\n", .{dest});
    return true;
}

pub fn ensureArtifactLayout() !bool {
    const io = try zion_root.getIo();
    const cwd = Dir.cwd();

    const paths = [_][]const u8{
        ".zion/ghostspec",
        ".zion/ghostspec/corpus",
        ".zion/ghostspec/crashes",
        ".zion/ghostspec/reports",
    };

    var created = false;

    for (paths) |path| {
        cwd.access(io, path, .{}) catch |err| switch (err) {
            error.FileNotFound => {
                cwd.createDirPath(io, path) catch |create_err| {
                    if (create_err != error.PathAlreadyExists) return create_err;
                };
                created = true;
            },
            else => return err,
        };
    }

    try createGitKeep(".zion/ghostspec/corpus/.gitkeep");
    try createGitKeep(".zion/ghostspec/crashes/.gitkeep");
    try createGitKeep(".zion/ghostspec/reports/.gitkeep");

    return created;
}

pub fn executeWorkflow(allocator: Allocator, mode: RunMode, extra_args: []const []const u8) CommandFailed!void {
    const io = zion_root.getIo() catch return CommandFailed.CommandFailed;

    var args: std.ArrayListUnmanaged([]const u8) = .empty;
    defer args.deinit(allocator);

    args.appendSlice(allocator, &.{ "zig", "build", "ghostspec-test" }) catch {
        return CommandFailed.CommandFailed;
    };
    args.appendSlice(allocator, extra_args) catch {
        return CommandFailed.CommandFailed;
    };

    _ = ensureArtifactLayout() catch {
        return CommandFailed.CommandFailed;
    };

    switch (mode) {
        .fuzz => try ensureFilter(&args, allocator, "ghostspec/fuzz:"),
        .bench => try ensureFilter(&args, allocator, "ghostspec/bench:"),
        .report => {
            try ensureForwardSeparator(&args, allocator);
            if (!sliceHasToken(args.items[3..], "--format")) {
                args.append(allocator, "--format") catch return CommandFailed.CommandFailed;
                args.append(allocator, "json") catch return CommandFailed.CommandFailed;
            }
            if (!sliceHasToken(args.items[3..], "--report-path")) {
                args.append(allocator, "--report-path") catch return CommandFailed.CommandFailed;
                args.append(allocator, default_report_path) catch return CommandFailed.CommandFailed;
            }
        },
        .ci => {
            try ensureForwardSeparator(&args, allocator);
            if (!sliceHasToken(args.items[3..], "--ci-profile")) {
                args.append(allocator, "--ci-profile") catch return CommandFailed.CommandFailed;
                args.append(allocator, "default") catch return CommandFailed.CommandFailed;
            }
        },
        .run => {},
    }

    var child = std.process.spawn(io, .{
        .argv = args.items,
        .stdin = .ignore,
        .stdout = .inherit,
        .stderr = .inherit,
    }) catch {
        return CommandFailed.SpawnFailed;
    };

    const term = child.wait(io) catch {
        return CommandFailed.CommandFailed;
    };

    switch (term) {
        .exited => |code| {
            if (code != 0) {
                std.debug.print("GhostSpec workflow exited with code {d}.\n", .{code});
                return CommandFailed.CommandFailed;
            }
        },
        .signal => |sig| {
            std.debug.print("GhostSpec workflow interrupted by signal {d}.\n", .{sig});
            return CommandFailed.CommandFailed;
        },
        else => return CommandFailed.CommandFailed,
    }
}

fn ensureDependency(allocator: Allocator, update: bool) !bool {
    var zon = manifest.ZonFile.loadFromFile(allocator, "build.zig.zon") catch |err| {
        if (err == error.FileNotFound) {
            std.debug.print("build.zig.zon not found. Run 'zion init' first.\n", .{});
        }
        return err;
    };
    defer zon.deinit();

    const already = zon.dependencies.contains("ghostspec");
    if (already and !update) {
        std.debug.print("GhostSpec dependency already present.\n", .{});
        return false;
    }

    const add_opts = add_cmd.AddOptions{
        .auto_integrate = false,
        .update_if_exists = update,
    };
    try add_cmd.add(allocator, "ghostkellz/ghostspec", add_opts);
    return true;
}

fn buildSnippet() []const u8 {
    return build_wiring_snippet;
}

fn createGitKeep(path: []const u8) !void {
    const io = try zion_root.getIo();
    const cwd = Dir.cwd();
    const file = cwd.createFile(io, path, .{ .exclusive = true }) catch |err| switch (err) {
        error.PathAlreadyExists => return,
        else => return err,
    };
    file.close(io);
}

fn ensureFilter(args: *std.ArrayListUnmanaged([]const u8), allocator: Allocator, pattern: []const u8) CommandFailed!void {
    if (sliceHasToken(args.items[3..], "--test-filter")) {
        return;
    }
    try ensureForwardSeparator(args, allocator);
    args.append(allocator, "--test-filter") catch return CommandFailed.CommandFailed;
    args.append(allocator, pattern) catch return CommandFailed.CommandFailed;
}

fn ensureForwardSeparator(args: *std.ArrayListUnmanaged([]const u8), allocator: Allocator) CommandFailed!void {
    if (sliceHasToken(args.items[3..], "--")) {
        return;
    }
    args.append(allocator, "--") catch return CommandFailed.CommandFailed;
}

fn sliceHasToken(slice: []const []const u8, token: []const u8) bool {
    for (slice) |item| {
        if (std.mem.eql(u8, item, token)) return true;
    }
    return false;
}

pub fn manifestSummary() ghostspec_pkg.zion.Manifest {
    return ghostspec_pkg.zion.manifest();
}
